version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "WEB-FARMACIA"
s3_bucket = "farmacia.ventas"
s3_prefix = "WEB-FARMACIA/v1"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "UserPoolID=\"us-east-1_6jVt6odpf\" ClientPoolID=\"6lnpq4ksu7pfiuhda5jekgt8mt\""
