version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "WEB-FARMACIA"
s3_bucket = "farmacia.ventas"
s3_prefix = "WEB-FARMACIA"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "UserPoolID=\"us-east-1_MtBddKTvm\" ClientPoolID=\"4s34hq0821fb08c30o4fk5gfp5\""
