AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-cli

  Sample SAM Template for sam-cli
  

Globals:
  Function:
    Timeout: 10
    Runtime: nodejs14.x
    CodeUri: src/

Parameters:
  UserPoolID:
    Type: String
    Description: "User pool ID del cognito"
    Default: "us-east-1_BjPuLlp8T"
  ClientPoolID:
    Type: String
    Description: "Client pool ID del cognito"
    Default: "7k0knf5jdl6cc185irnr00rusn"
  TableUser:
    Type: String
    Description : "Tabla usuario en Dynamo, donde se ecnuentran los usuarios"
    Default : "FARMACIA-USUARIOS"

Resources:
  PruebaFunction:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: 'Farmacia-PruebaFunction'
      Handler: handler/prueba.lambdaHandler
      Events:
        HelloWorld:
          Type: Api 
          Properties:
            Path: /prueba
            Method: get
            RestApiId: !Ref AutorizacionFunction
            Auth :
              Authorizer : "MyCognitoAuth"

  # Login 
  LoginFunction:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: 'Farmacia-LoginFunction'
      Handler: handler/login/login.token
      Environment:
        Variables:
          USER_POOL_ID : !Ref UserPoolID
          CLIENT_POOL : !Ref ClientPoolID
          TABLE_USER : !Ref TableUser
      Events:
        Login:
          Type: Api 
          Properties:
            Path: /token
            Method: post
            RestApiId: !Ref AutorizacionFunction
      Policies:
        - AmazonCognitoReadOnly
        - AmazonCognitoPowerUser

  StatusFunction:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: 'Farmacia-StatusFunction'
      Handler: handler/login/login.statusToken
      Events:
        Login:
          Type: Api 
          Properties:
            Path: /status
            Method: get
            RestApiId: !Ref AutorizacionFunction
            Auth :
              Authorizer : "MyCognitoAuth"
      Policies:
        - AmazonCognitoReadOnly
        - AmazonCognitoPowerUser
  
  # Contrasenia
  CambiarContraseniaFunction:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: 'Farmacia-CambiarContraseniaFunction'
      Handler: handler/login/contrasenia.cambiarContraseniaPrimeraVez
      Environment:
        Variables:
          USER_POOL_ID : !Ref UserPoolID
          CLIENT_POOL : !Ref ClientPoolID
      Events:
        Login:
          Type: Api  
          Properties:
            Path: /password/update
            Method: put
            RestApiId: !Ref AutorizacionFunction
      Policies:
        - AmazonCognitoReadOnly
        - AmazonCognitoPowerUser
  CambiarContraseniaAdminFunction:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: 'Farmacia-CambiarContraseniaAdminFunction'
      Handler: handler/login/contrasenia.cambiarContraseniaAdmin
      Environment:
        Variables:
          USER_POOL_ID : !Ref UserPoolID
      Events:
        Login:
          Type: Api  
          Properties:
            Path: /password
            Method: put
            RestApiId: !Ref AutorizacionFunction
            Auth :
              Authorizer : "MyCognitoAuth"
      Policies:
        - AmazonCognitoReadOnly
        - AmazonCognitoPowerUser
  
  # Usario
  MeFunction:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: 'Farmacia-Me'
      Handler: handler/login/usuarios.me
      Events:
        Login:
          Type: Api  
          Properties:
            Path: /me
            Method: get
            RestApiId: !Ref AutorizacionFunction
            Auth :
              Authorizer : "MyCognitoAuth"
      Policies:
        - AmazonCognitoReadOnly
        - AmazonCognitoPowerUser
  CrearUsuarioFunction:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: 'Farmacia-CrearUsuario'
      Handler: handler/login/usuarios.crearUsuario
      Environment:
        Variables:
          USER_POOL_ID : !Ref UserPoolID
      Events:
        Login:
          Type: Api  
          Properties:
            Path: /user/create
            Method: post
            RestApiId: !Ref AutorizacionFunction
            Auth :
              Authorizer : "MyCognitoAuth"
      Policies:
        - AmazonCognitoReadOnly
        - AmazonCognitoPowerUser
  ListaUsuariosFunction:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: 'Farmacia-ListarUsuarios'
      Handler: handler/login/usuarios.obtenerUsuarios
      Environment:
        Variables:
          USER_POOL_ID : !Ref UserPoolID
      Events:
        ListUsersEvent:
          Type: Api  
          Properties:
            Path: /user
            Method: get
            RestApiId: !Ref AutorizacionFunction
            Auth :
              Authorizer : "MyCognitoAuth"
      Policies:
        - AmazonCognitoReadOnly
        - AmazonCognitoPowerUser

  #Autorizador creado en API Gateway para cognito
  AutorizacionFunction:
    Type: AWS::Serverless::Api
    Properties:
      Name: AutorizacionCognito
      StageName: dev
      GatewayResponses:
        UNAUTHORIZED:
          StatusCode: 401
          ResponseParameters:
            Headers:
              Access-Control-Allow-Methods: "'GET,HEAD,PUT,PATCH,POST,DELETE,OPTIONS'"
              Access-Control-Allow-Headers: "'Origin, X-Requested-With, Content-Type, Accept, Authorization'"
              Access-Control-Allow-Origin: "'*'"
          ResponseTemplates:
            "application/json": '{ "message": $context.error.messageString ,"code": "0001" }'
        EXPIRED_TOKEN:
          StatusCode: 401
          ResponseParameters:
            Headers:
              Access-Control-Allow-Methods: "'GET,HEAD,PUT,PATCH,POST,DELETE,OPTIONS'"
              Access-Control-Allow-Headers: "'Origin, X-Requested-With, Content-Type, Accept, Authorization'"
              Access-Control-Allow-Origin: "'*'"
          ResponseTemplates:
            "application/json": '{ "message": $context.error.messageString ,"code": "0002" }'
        INTEGRATION_TIMEOUT:
          StatusCode: 504
          ResponseParameters:
            Headers:
              Access-Control-Allow-Methods: "'GET,HEAD,PUT,PATCH,POST,DELETE,OPTIONS'"
              Access-Control-Allow-Headers: "'Origin, X-Requested-With, Content-Type, Accept, Authorization'"
              Access-Control-Allow-Origin: "'*'"
          ResponseTemplates:
            "application/json": '{ "message": $context.error.messageString ,"code": "0003" }'             
      Cors:
        AllowMethods: "'GET,HEAD,PUT,PATCH,POST,DELETE,OPTIONS'"
        AllowHeaders: "'Origin, X-Requested-With, Content-Type, Accept, Authorization'"
        AllowOrigin: "'*'"      
      TracingEnabled: true
      Auth :
        Authorizers: 
          MyCognitoAuth :
            UserPoolArn : !Sub "arn:aws:cognito-idp:us-east-1:${AWS::AccountId}:userpool/${UserPoolID}"

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  #HelloWorldApi:
    #Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    #Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  #HelloWorldFunction:
    #Description: "Hello World Lambda Function ARN"
    #Value: !GetAtt HelloWorldFunction.Arn
  #HelloWorldFunctionIamRole:
    #Description: "Implicit IAM Role created for Hello World function"
    #Value: !GetAtt HelloWorldFunctionRole.Arn
  StackName:
    Description: 'Stack name.'
    Value: !Sub '${AWS::StackName}'
  ApiEndpoint:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub
      - 'https://${AutorizacionFunction}.execute-api.${AWS::Region}.amazonaws.com/${Stage}'
      - Stage: dev
  ApiId:
    Description: 'Api ID'
    Value: !Sub '${AutorizacionFunction}'
